apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/2b6251dfedb54de40596272a73ed1fb19d740219/manifests/ha/install.yaml # v3.2.3
  - https://github.com/argoproj/argo-workflows/releases/download/v3.7.2/install.yaml
