name: sandbox / caller

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}--${{ github.ref }}
  cancel-in-progress: true

jobs:
  a:
    uses: ./.github/workflows/sandbox.yaml
    concurrency:
      group: ${{ github.workflow }}--${{ github.ref }}--a
      cancel-in-progress: true
  b:
    uses: ./.github/workflows/sandbox.yaml
    concurrency:
      group: ${{ github.workflow }}--${{ github.ref }}--b
      cancel-in-progress: true
  c:
    uses: ./.github/workflows/sandbox.yaml
    concurrency:
      group: ${{ github.workflow }}--${{ github.ref }}--c
      cancel-in-progress: true
